--SCRIPT DE IMPORTAÇÃO SC6

USE [PROTHEUS_TST]
GO

INSERT INTO [dbo].[SC6010]
           ([C6_FILIAL]
           ,[C6_ITEM]
           ,[C6_PRODUTO]
           ,[C6_UM]
           ,[C6_QTDVEN]
           ,[C6_PRCVEN]
           ,[C6_VALOR]
           ,[C6_QTDLIB]
           ,[C6_QTDLIB2]
           ,[C6_SEGUM]
           ,[C6_TES]
           ,[C6_UNSVEN]
           ,[C6_LOCAL]
           ,[C6_CF]
           ,[C6_QTDENT]
           ,[C6_QTDENT2]
           ,[C6_CLI]
           ,[C6_DESCONT]
           ,[C6_VALDESC]
           ,[C6_ENTREG]
           ,[C6_LA]
           ,[C6_LOJA]
           ,[C6_NOTA]
           ,[C6_SERIE]
           ,[C6_DATFAT]
           ,[C6_NUM]
           ,[C6_COMIS1]
           ,[C6_COMIS2]
           ,[C6_COMIS3]
           ,[C6_COMIS4]
           ,[C6_COMIS5]
           ,[C6_PEDCLI]
           ,[C6_DESCRI]
           ,[C6_PRUNIT]
           ,[C6_BLOQUEI]
           ,[C6_RESERVA]
           ,[C6_OP]
           ,[C6_OK]
           ,[C6_NFORI]
           ,[C6_SERIORI]
           ,[C6_ITEMORI]
           ,[C6_IPIDEV]
           ,[C6_IDENTB6]
           ,[C6_BLQ]
           ,[C6_PICMRET]
           ,[C6_CODISS]
           ,[C6_GRADE]
           ,[C6_ITEMGRD]
           ,[C6_LOTECTL]
           ,[C6_NUMLOTE]
           ,[C6_DTVALID]
           ,[C6_NUMORC]
           ,[C6_CHASSI]
           ,[C6_OPC]
           ,[C6_LOCALIZ]
           ,[C6_NUMSERI]
           ,[C6_NUMOP]
           ,[C6_ITEMOP]
           ,[C6_CLASFIS]
           ,[C6_QTDRESE]
           ,[C6_CONTRAT]
           ,[C6_NUMOS]
           ,[C6_NUMOSFA]
           ,[C6_CODFAB]
           ,[C6_LOJAFA]
           ,[C6_ITEMCON]
           ,[C6_TPOP]
           ,[C6_REVISAO]
           ,[C6_SERVIC]
           ,[C6_ENDPAD]
           ,[C6_TPESTR]
           ,[C6_CONTRT]
           ,[C6_TPCONTR]
           ,[C6_ITCONTR]
           ,[C6_GEROUPV]
           ,[C6_PROJPMS]
           ,[C6_EDTPMS]
           ,[C6_TASKPMS]
           ,[C6_TRT]
           ,[C6_QTDEMP]
           ,[C6_QTDEMP2]
           ,[C6_PROJET]
           ,[C6_ITPROJ]
           ,[C6_POTENCI]
           ,[C6_LICITA]
           ,[C6_REGWMS]
           ,[C6_MOPC]
           ,[C6_NUMCP]
           ,[C6_NUMSC]
           ,[C6_ITEMSC]
           ,[C6_SUGENTR]
           ,[C6_ITEMED]
           ,[C6_ABSCINS]
           ,[C6_ABATISS]
           ,[C6_ABATMAT]
           ,[C6_VLIMPOR]
           ,[C6_FUNRURA]
           ,[C6_FETAB]
           ,[C6_CODROM]
           ,[C6_PROGRAM]
           ,[C6_TURNO]
           ,[C6_PEDCOM]
           ,[C6_ITPC]
           ,[C6_FILPED]
           ,[C6_DTFIMNT]
           ,[C6_FCICOD]
           ,[C6_DATAEMB]
           ,[C6_CODLAN]
           ,[C6_FORDED]
           ,[C6_LOJDED]
           ,[C6_NUMPCOM]
           ,[C6_ORCGAR]
           ,[C6_GCPIT]
           ,[C6_GCPLT]
           ,[C6_HORCPL]
           ,[C6_HORENT]
           ,[C6_ITEMPC]
           ,[C6_ITEMGAR]
           ,[C6_INTROT]
           ,[C6_ITEMCTA]
           ,[C6_ALMTERC]
           ,[C6_BASVEIC]
           ,[C6_CLVL]
           ,[C6_CONTA]
           ,[C6_CTVAR]
           ,[C6_DATCPL]
           ,[C6_ABATINS]
           ,[C6_CATEG]
           ,[C6_CC]
           ,[C6_CCUSTO]
           ,[C6_VDMOST]
           ,[C6_VDOBS]
           ,[C6_PENE]
           ,[C6_PVCOMOP]
           ,[C6_TNATREC]
           ,[C6_SOLCOM]
           ,[C6_PMSID]
           ,[C6_PCDED]
           ,[C6_MOTDED]
           ,[C6_NFDED]
           ,[C6_SERDED]
           ,[C6_RATEIO]
           ,[C6_VLDED]
           ,[C6_TPDEDUZ]
           ,[C6_VLNFD]
           ,[C6_TPPROD]
           ,[C6_TPREPAS]
           ,[C6_REVPROD]
           ,[C6_SDOC]
           ,[C6_SDOCDED]
           ,[C6_SDOCORI]
           ,[C6_SDOCSD1]
           ,[C6_PRODFIN]
           ,[C6_NRSEQCQ]
           ,[C6_PEDVINC]
           ,[C6_ITLPRE]
           ,[C6_GRPNATR]
           ,[C6_IPITRF]
           ,[C6_CSTPIS]
           ,[C6_CULTRA]
           ,[C6_D1DOC]
           ,[C6_D1ITEM]
           ,[C6_D1SERIE]
           ,[C6_CNATREC]
           ,[C6_CODLPRE]
           ,[C6_CODINF]
           ,[D_E_L_E_T_]
           ,[R_E_C_N_O_]
           ,[R_E_C_D_E_L_]
           ,[C6_BRICMS]
           ,[C6_CODPRCL]
           ,[C6_ICMSRET]
           ,[C6_XMEDIDA]
           ,[C6_XOBSPED])
     SELECT
          	C6_FILIAL 
           ,C6_ITEM 
           ,C6_PRODUTO 
           ,C6_UM 
           ,C6_QTDVEN 
           ,C6_PRCVEN 
           ,C6_VALOR 
           ,C6_QTDLIB 
           ,C6_QTDLIB2 
           ,C6_SEGUM 
           ,C6_TES 
           ,C6_UNSVEN 
           ,C6_LOCAL 
           ,C6_CF 
           ,C6_QTDENT 
           ,C6_QTDENT2 
           ,C6_CLI 
           ,C6_DESCONT 
           ,C6_VALDESC 
           ,C6_ENTREG 
           ,C6_LA 
           ,C6_LOJA 
           ,C6_NOTA 
           ,C6_SERIE 
           ,C6_DATFAT 
           ,C6_NUM 
           ,C6_COMIS1 
           ,C6_COMIS2 
           ,C6_COMIS3 
           ,C6_COMIS4 
           ,C6_COMIS5 
           ,C6_PEDCLI 
           ,C6_DESCRI 
           ,C6_PRUNIT 
           ,C6_BLOQUEI 
           ,C6_RESERVA 
           ,C6_OP 
           ,C6_OK 
           ,C6_NFORI 
           ,C6_SERIORI 
           ,C6_ITEMORI 
           ,C6_IPIDEV 
           ,C6_IDENTB6 
           ,C6_BLQ 
           ,C6_PICMRET 
           ,C6_CODISS 
           ,C6_GRADE 
           ,C6_ITEMGRD 
           ,C6_LOTECTL 
           ,C6_NUMLOTE 
           ,C6_DTVALID 
           ,C6_NUMORC 
           ,C6_CHASSI 
           ,C6_OPC 
           ,C6_LOCALIZ 
           ,C6_NUMSERI 
           ,C6_NUMOP 
           ,C6_ITEMOP 
           ,C6_CLASFIS 
           ,C6_QTDRESE 
           ,C6_CONTRAT 
           ,C6_NUMOS 
           ,C6_NUMOSFA 
           ,C6_CODFAB 
           ,C6_LOJAFA 
           ,C6_ITEMCON 
           ,C6_TPOP 
           ,C6_REVISAO 
           ,C6_SERVIC 
           ,C6_ENDPAD 
           ,C6_TPESTR 
           ,C6_CONTRT 
           ,C6_TPCONTR 
           ,C6_ITCONTR 
           ,C6_GEROUPV 
           ,C6_PROJPMS 
           ,C6_EDTPMS 
           ,C6_TASKPMS 
           ,C6_TRT 
           ,C6_QTDEMP 
           ,C6_QTDEMP2 
           ,C6_PROJET 
           ,C6_ITPROJ 
           ,C6_POTENCI 
           ,C6_LICITA 
           ,C6_REGWMS 
           ,C6_MOPC 
           ,C6_NUMCP 
           ,C6_NUMSC 
           ,C6_ITEMSC 
           ,C6_SUGENTR 
           ,C6_ITEMED 
           ,C6_ABSCINS 
           ,C6_ABATISS 
           ,C6_ABATMAT 
           ,C6_VLIMPOR 
           ,C6_FUNRURA 
           ,C6_FETAB 
           ,C6_CODROM 
           ,C6_PROGRAM 
           ,C6_TURNO 
           ,C6_PEDCOM 
           ,C6_ITPC 
           ,C6_FILPED 
           ,C6_DTFIMNT 
           ,C6_FCICOD 
           ,C6_DATAEMB 
           ,C6_CODLAN 
           ,C6_FORDED 
           ,C6_LOJDED 
           ,C6_NUMPCOM 
           ,C6_ORCGAR 
           ,C6_GCPIT 
           ,C6_GCPLT 
           ,C6_HORCPL 
           ,C6_HORENT 
           ,C6_ITEMPC 
           ,C6_ITEMGAR 
           ,C6_INTROT 
           ,C6_ITEMCTA 
           ,C6_ALMTERC 
           ,C6_BASVEIC 
           ,C6_CLVL 
           ,C6_CONTA 
           ,C6_CTVAR 
           ,C6_DATCPL 
           ,C6_ABATINS 
           ,C6_CATEG 
           ,C6_CC 
           ,C6_CCUSTO 
           ,C6_VDMOST 
           ,C6_VDOBS 
           ,C6_PENE 
           ,C6_PVCOMOP 
           ,C6_TNATREC 
           ,C6_SOLCOM 
           ,C6_PMSID 
           ,C6_PCDED 
           ,C6_MOTDED 
           ,C6_NFDED 
           ,C6_SERDED 
           ,C6_RATEIO 
           ,C6_VLDED 
           ,C6_TPDEDUZ 
           ,C6_VLNFD 
           ,C6_TPPROD 
           ,C6_TPREPAS 
           ,C6_REVPROD 
           ,C6_SDOC 
           ,C6_SDOCDED 
           ,C6_SDOCORI 
           ,C6_SDOCSD1 
           ,C6_PRODFIN 
           ,C6_NRSEQCQ 
           ,C6_PEDVINC 
           ,C6_ITLPRE 
           ,C6_GRPNATR 
           ,C6_IPITRF 
           ,C6_CSTPIS 
           ,C6_CULTRA 
           ,C6_D1DOC 
           ,C6_D1ITEM 
           ,C6_D1SERIE 
           ,C6_CNATREC 
           ,C6_CODLPRE 
           ,C6_CODINF 
           ,D_E_L_E_T_ 
           ,R_E_C_N_O_ 
           ,R_E_C_D_E_L_ 
           ,C6_BRICMS 
           ,C6_CODPRCL 
           ,C6_ICMSRET 
           ,C6_XMEDIDA 
           ,C6_XOBSPED 
		   FROM 
		   DADOSP12117.dbo.SC6010 SC6FUN
		   
		   WHERE SC6FUN.D_E_L_E_T_ = ''
		   AND SC6FUN.C6_NUM IN ( SELECT C5_XNUMANT FROM PROTHEUS_TST.dbo.SC5010 C5FULL WHERE C5FULL.C5_NOTA = '' and C5FULL.D_E_L_E_T_ = '')
		   and SC6FUN.C6_QTDENT < SC6FUN.C6_QTDVEN
		  
GO

			--UPDATE SC6010 SET C6_XNUMANT= C6_NUM

			--UPDATE SC6010 SET  C6_NUM = (SELECT C5_NUM FROM SC5010 WHERE C5_XNUMANT = C6_XNUMANT)

			SELECT * FROM SC6010




